version = 1
SPDX-PackageName = "Praefectus"
SPDX-PackageSupplier = "Friedrich von Never <friedrich@fornever.me>"
SPDX-PackageDownloadLocation = "https://github.com/ForNeVeR/Praefectus"

[[annotations]]
path = ".idea/**/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**.DotSettings"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"
