name: Main
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [macos-10.15, ubuntu-18.04, windows-2019]
        include:
          - image: macos-10.15
            rid: osx-x64
            executable: praefectus
          - image: ubuntu-18.04
            rid: linux-x64
            executable: praefectus
          - image: windows-2019
            rid: win-x64
            executable: praefectus.exe
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - uses: actions/checkout@v2

      - name: NuGet Cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.101'

      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release
      - name: Publish Self-Contained Distribution
        run: dotnet publish --runtime ${{ matrix.rid }} --self-contained true --configuration Release --output publish -p:PublishTrimmed=true Praefectus.Console
      - name: Integration Test After Publish
        run: dotnet test --configuration Release Praefectus.IntegrationTests
        env:
          PRAEFECTUS_TEST_EXECUTABLE: "${{ github.workspace }}/publish/${{ matrix.executable }}"
      - name: Publish Framework-Dependent Distribution
        run: dotnet publish --runtime ${{ matrix.rid }} --self-contained false --configuration Release --output publish.fd Praefectus.Console

      - name: Get Version
        shell: pwsh
        run: |
          $version = ./scripts/Get-Version.ps1
          "PRAEFECTUS_VERSION=$version" >> $env:GITHUB_ENV
      - name: Upload Self-Contained Distribution
        uses: actions/upload-artifact@v2
        with:
          name: praefectus.${{ env.PRAEFECTUS_VERSION }}.${{ matrix.rid }}
          path: publish
      - name: Upload Framework-Dependent Distribution
        uses: actions/upload-artifact@v2
        with:
          name: praefectus.fd.${{ env.PRAEFECTUS_VERSION }}.${{ matrix.rid }}
          path: publish.fd
