name: Main
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [macos-10.15, ubuntu-18.04, windows-2019]
        include:
          - image: macos-10.15
            rid: osx-x64
            executable: praefectus
          - image: ubuntu-18.04
            rid: linux-x64
            executable: praefectus
          - image: windows-2019
            rid: win-x64
            executable: praefectus.exe
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - uses: actions/checkout@v2

      - name: NuGet Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release
