# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

name: Main
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          # renovate:
          - macos-14
          # renovate:
          - ubuntu-24.04
          # renovate:
          - windows-2025
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - uses: actions/checkout@v5

      - name: NuGet Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release

  encoding:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v5
      - name: Verify encoding
        shell: pwsh
        run: scripts/Test-Encoding.ps1

  licenses:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v5
      - name: REUSE license check
        uses: fsfe/reuse-action@v5
