# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

name: Main
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [macos-13, ubuntu-20.04, windows-2019]
        include:
          - image: macos-13
            rid: osx-x64
            executable: praefectus
          - image: ubuntu-20.04
            rid: linux-x64
            executable: praefectus
          - image: windows-2019
            rid: win-x64
            executable: praefectus.exe
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - uses: actions/checkout@v4

      - name: NuGet Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release

  encoding:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4
      - name: Verify encoding
        shell: pwsh
        run: scripts/Test-Encoding.ps1

  licenses:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4
      - name: REUSE license check
        uses: fsfe/reuse-action@v5
